spring.application.name=demo
spring.application.jwt.key=1ytvns7A2HHo2GUQ2d82xS2I7dRyWWv1BTU51Ve+il0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Core PayOS credentials
payos.client-id=f9cbb83b-0b45-49ac-86d1-f560863fd658
payos.api-key=0953bd92-dcde-433d-8f1d-10fbcc66f445
payos.checksum-key=07005bb8bd2cdb16e5ecf8d7aa7e2a9af01314aa394f04fa5166f2ac88448699

payos.payout-client-id=
payos.payout-api-key=
payos.payout-checksum-key=
payos.log-level=NONE
# Cloudinary
cloudinary.api-key=455432165327886
cloudinary.api-secret=HN0NF2Cf-D6usfDQmJuV-TIKZdk
cloudinary.name=mydinnerproject

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mydinnerproject?currentSchema=public
spring.datasource.username=admin
spring.datasource.password=123

#key jwt
rsa.rsa-private-key=C:/Users/Yato/Desktop/Project Yukihira Restaurant/back-end/src/main/java/com/example/demo/key_jwt/private_key_pkcs8.pem
rsa.rsa-public-key=C:/Users/Yato/Desktop/Project Yukihira Restaurant/back-end/src/main/java/com/example/demo/key_jwt/public_key.pem

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yukihirayato2003@gmail.com
spring.mail.password=lzrc ohon rqtz vhmo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#log
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2: DEBUG